### ISSUE TITLE
 Game request: Kajiri Kamui Kagura

### ISSUE THREAD

**Issue by kiraduwang** [morkt/GARbro#137]
This version specifically.

神咒神威神楽 曙之光 初回版

I can't access all the cgs because its missing the title key.

**Comment by morkt** [comment]
Kajiri Kamui Kagura is upported for a long time. make sure to use [the latest release.](https://github.com/morkt/GARbro/releases/latest)

some CGs may not be automatically displayed because textures are scattered through different archives. in that case, you'll have to extract everything into one directory with no image conversion (choose "as is" format in extraction dialog), then go that directory and convert images from there.

**Comment by kiraduwang** [comment]
>you'll have to extract everything into one directory with no image conversion (choose "as is" format in extraction dialog), then go that directory and convert images from there.

This didn't work, unless you mean extract all of the data files.

**Comment by morkt** [comment]
yes, i mean all data files from ALL archives.

**Comment by kiraduwang** [comment]
Alright, that fixed it. Thanks

**Comment by kiraduwang** [comment]
Hmm actually I ge
![error](https://user-images.githubusercontent.com/35320906/35330177-89e9b508-00d0-11e8-8e40-39e5d66417ee.PNG)
t this error when I try to extract them.

**Comment by morkt** [comment]
to convert images use 'convert multimedia' function (`F6` key).
