### ISSUE TITLE
New decryption of Game 'Riddle Joker' from Yuzusoft seem to have some error

### ISSUE THREAD

**Issue by thddygks33** [morkt/GARbro#170]
I always appriciate about all this work. very thanks everybody contribute with garbro

I found GARbro now has decryption about game 'Riddle Joker' from Yuzu Soft.

but I get some error when I unpack riddle joker's 1.10 patch.xp3 and repack any .xp3 file.

*original error message is korean. I translated it arbitrarily
when I unpack riddle joker's 1.10 patch.xp3, I get following error many time:
'file kido413_011.ogg.sil is already exist' and so on
and passing that, next error occur,
'error occur when file extraction, 
\ scnchart.func
\ output character buffer is too small to contain encoded character. encoding 'Unicode' replaced.(fall back)
\ 'System.Text.DecoderReplacementFallback'.
\ paramater name : chars

and another, when I repack riddle joker's any version's any file. the game say this file is invalid and can't start game.
even when I never touch any resource in .xp3 file, repacking resulted same error.

please help me solve this problem out

**Comment by ForsakenRei** [comment]
It works fine for me to unpack patch xp3 files but I didn't try repack.

Maybe you can try other method such as universal patch provided by KrkrExtrat.

**Comment by haniwa55** [comment]
The text file extracted by GARbro has an error in some bytes at head of file.
As a result, GARbro can not browse some text files.
The following figure extracted AppConfig.tjs of data.xp3 and compares it with a binary editor and a text editor.
![garbro](https://user-images.githubusercontent.com/35873133/38414720-3bedde1e-39ca-11e8-9f58-1e3c058dba85.png)

I think this issue is related to the error in  some bytes at head of file.

**Comment by ForsakenRei** [comment]
I found both GARbro and KrE cannot read the pbd files which store all the locations for the character bodies/faces in fgimage.xp3. They changed encryption method some place.
