### ISSUE TITLE
Game request: Nukige Mitai na Shima ni Sunderu Watashi wa Dou Surya Ii Desu ka?

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#207]
VNDB: https://vndb.org/v22899
Developer: Qruppo
Engine: 椎名里猪 v2.50
Archive files: .WAR

Thank you so much!

![2](https://user-images.githubusercontent.com/26744056/43357221-dc880434-9286-11e8-9199-9f0e1e20a643.png)

**Comment by morkt** [comment]
you may download updated formats database using 'check for updates' menu option.

**Comment by Veshurik** [comment]
Thanks, updated, but some files still can't be seen.
![1](https://user-images.githubusercontent.com/26744056/43446637-11bec53e-94b2-11e8-93ff-52cdc83ab213.png)

**Comment by morkt** [comment]
that's usual for WAR archives, they contain bogus entries as part of archive protection. if you happen to know a reliable way to tell them apart from regular entries, i could add a filter for them, otherwise just ignore them.

**Comment by Veshurik** [comment]
Can you also add support for trial version? Thanks!

**Comment by marcussacana** [comment]
@morkt Since if can't think in a trustable way to filter this fake file, what about do a random detection just to put a tag of  'possible trap file' in the type description, if he fails to detect will be not a problem, maybe just detect the filename that contains only 1 non-ascii character and failed to get the preview...?

**Comment by morumoto** [comment]
#376 
The next version came out.

**Comment by parasaite** [comment]
Excuse me, how can I add a filter?
