### ISSUE TITLE
Extracting IMG/BGM/SE from https://vndb.org/r791 works but not scripts

### ISSUE THREAD

**Issue by Ileca** [morkt/GARbro#213]
I assume the script is located in spt/.
I will have the need for others Black Cy c's scripts too, assuming it doesn't work for them too and the solution is per game.

Thanks in advance.

PS: Is it me or Garbro tend to focus on graphic and sound files and forget scripts? No accusation, just find that weird like it's not the first time I see that, what made me wonder if it was by design, scripts being rarely extracted by people (not only scenario script but also engine related stuff)?

**Comment by morkt** [comment]
first, garbro workflow is centered around archives, those particular scripts are not inside archives, so look for other tools to decompile them. second, game script decompilation is a feat of its own and i'm not particularly interested implementing it because of how time consuming such task would be.
