### ISSUE TITLE
Ethornell: DSC compression not recognized in archive version 2.0

### ISSUE THREAD

**Issue by arcusmaximus** [morkt/GARbro#220]
For the Ethornell engine, GARbro supports both the old archive format ("Pack") and the new one ("BURIKO ARC20"). While it recognizes and handles the "DSC FORMAT 1.00" compression signature for the old format, though, it doesn't do this for the new format - even though this scheme is still in use there.

In ARC20 archives, this "DSC" encryption can be either unencrypted (like in "Pack" archives) or encrypted ("BSE" encryption applied after compression). An example of the former is 大図書館の羊飼い～放課後しっぽデイズ (sysgrp.arc). An example of the latter is 蒼の彼方のフォーリズム.

**Comment by morkt** [comment]
what do you mean by "not recognized"? "Ao no Kanata no Four Rhythm" archives are most certainly supported, so i'm not sure what you're talking about. maybe you've run into issue of files not marked as "images"? with BURIKO archives file type detection doesn't work since entries have no filename extensions, so you'll have to manually assign "image" type by selecting files and choosing corresponding option in a context menu.

**Comment by arcusmaximus** [comment]
My bad - it's indeed simply a matter of file type detection. While GARBro automatically marks files as images if they're encrypted, it doesn't do this if they're compressed. Once they're manually marked as images, though, they get displayed just fine.

Unless you feel like adding automatic image detection (as e.g. the ExtractData tool does - https://github.com/lioncash/ExtractData/blob/master/Extract/Ethornell.cpp), you can close this ticket.
