### ISSUE TITLE
Request: Complet's C4 engine MPX scenario files

### ISSUE THREAD

**Issue by ferniksu** [morkt/GARbro#288]
Hello, about the Complet's / Authoring Heaven old VN's working with the C4.exe engine, almost all files can be extracted (Images and sound), but the scenario files with ".MPX" extension can't be extracted at the moment, I tested some VN's with the Shiina Rio Engine and the scenario files could be extracted, which is great in order to translate them to English and port them to an Open Source engine like Ren'Py.

So basic request is if you could update GARbro to extract the Complet's C4 engine "MPX" scenario files, so they could be translated, thanks.

**Comment by morkt** [comment]
the term "extract" cannot be applied to these scripts, since they don't reside within any archive. what you're talking about is "decryption" or "decompilation". unfortunately, i have no plans implementing a workflow around standalone scripts processing. i can share, however, [this gist](https://gist.github.com/morkt/1ba5fd458ae65f8105d1a41709444dcc), make of it what you will.

**Comment by ferniksu** [comment]
Well thanks for looking at it, at the moment I'm a total potato on programming, so I don't think I can do a thing with the C+ script you publish on that gist, (I even had to google what's a ".cc", to understand that). But anyways, thanks for your time and sorry for the trouble.

**Comment by emmauss** [comment]
@ferniksu I have a c4 mpx decryptor, if you are interest.

**Comment by emmauss** [comment]
@morkt do you have any idea on what the variables in scripts do? like what these mean `%i%f,1;%e,97;%g,black;%e,10;%m,mnt0;%g,title;%w,5; %e,97;%g,black;%m,mnt0;%g,title;%w,5;`

**Comment by linakima** [comment]
@emmauss Hi, I'm looking for the c4 decrypter. Could you please share it with me?
