### ISSUE TITLE
Request: Sankaku Ren'ai: Love Triangle Trouble! (aka Suki to Suki to de Sankaku Ren’ai) AND fairy fencer f advent dark force 2D sprites HELP!!!

### ISSUE THREAD

**Issue by QBASpriteFinder** [morkt/GARbro#438]
I NEED HELP, getting the 2D Sprites from both Sankaku Ren'ai: Love Triangle Trouble! and  fairy fencer f advent dark force. But I can't seem to do it... I try to used the KrkrExtract to try and get the 2D sprites from Sankaku Ren'ai: Love Triangle Trouble! But they are all 0 byte files. I NEED HELP PLEASE!!!

**Comment by AsukaLangleyfag** [comment]
It's github page for GARbro tho. And GARbro can extract those real nice (use type of game "Kari Gurashi Ren'ai" with madocrypt), just make sure to convert them since they are in the tlg format. Also you would have to combine them, but "you're a big guy" you can figure that out on your own. Fairy fencer f advent dark force is NOT supported, so gotta find how to do that somewhere else. You can fix this request for that i guess, but i'm pretty sure there's other tools for the job.

**Comment by QBASpriteFinder** [comment]
How do I Get madocrypt?

**Comment by AsukaLangleyfag** [comment]
like this?

**Comment by QBASpriteFinder** [comment]
how do you activate Archive parameters? I double click and right click and it doesn't appear on my computer 
is it an installation of some sort?

**Comment by QBASpriteFinder** [comment]
THANK YOU VERY MUCH!
