### ISSUE TITLE
Game request: ISLAND DIARY (Steam)

### ISSUE THREAD

**Issue by Kafu-Yukimura** [morkt/GARbro#468]
VNDB : https://vndb.org/v21436
Developer : Watakubi & Sekai Project
Extension: .xp3 (kirikiri Z)

The source file of this game is encrypted.

**Comment by Kafu-Yukimura** [comment]
I can bypass encryption and extract via KrkrExtract.

**Comment by GuyInDogSuit** [comment]
How did you get this to work? I'm assuming you have the original release or maybe the Sekai censored one?
I'm trying to unpack the Steam patch from Denpasoft, but the issue is that the decryption seems to fail with both GARbro and KrkrExtract. The files can't be opened (though they all are sized correctly, it would seem, regardless).

**Comment by Kafu-Yukimura** [comment]
At the time, only the DVD-ROM version was tested.
However, for the Steam Version (Uncensored Version), krkrExtract doesn't seem to work.
Open the request again.

**Comment by Kafu-Yukimura** [comment]
@GuyInDogSuit I found a way again.
Get the Steam version crack yourself and run ISLAND DIARY through Krkrextract.
And drag the xp3 file to the Krkrextract window.
This way you can extract the files even if the game doesn't work.
Krkrextract used version 4.0.1.5.
